Update task into db

i've noticed that the app
throws an error if you don't
login (keyerror 'user')
